### ISSUE TITLE
"Error when launching multilang subprocess" with pyleus

### ISSUE THREAD

**Issue by nilakshdas** [miguno/wirbelsturm#29]
I encounter this error when submitting a topology with [pyleus](https://github.com/Yelp/pyleus).

```
2014-12-09 09:50:18 b.s.d.executor [ERROR] 
java.lang.RuntimeException: Error when launching multilang subprocess
pyleus_venv/bin/python: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

	at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:66) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.task.ShellBolt.prepare(ShellBolt.java:117) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.executor$fn__3441$fn__3453.invoke(executor.clj:692) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.util$async_loop$fn__464.invoke(util.clj:461) ~[storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:434) ~[na:1.7.0_71]
	at java.io.OutputStream.write(OutputStream.java:116) ~[na:1.7.0_71]
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.7.0_71]
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.7.0_71]
	at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.7.0_71]
	at com.yelp.pyleus.serializer.MessagePackSerializer.writeMessage(MessagePackSerializer.java:208) ~[stormjar.jar:na]
	at com.yelp.pyleus.serializer.MessagePackSerializer.connect(MessagePackSerializer.java:65) ~[stormjar.jar:na]
	at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:64) ~[storm-core-0.9.3.jar:0.9.3]
	... 5 common frames omitted
```

**Comment by miguno** [comment]
Closed because of inactivity.  Please reopen if you want to continue working on this.
