### ISSUE TITLE
aws-iam-tools deprecated 

### ISSUE THREAD

**Issue by nklugman** [miguno/wirbelsturm#30]
This breaks your aws-setup-iam script. I tried installing the deprecated library and got the error:

Creating Wirbelsturm IAM group...
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/services/auth/identity/cli/view/GroupCreateView
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.auth.identity.cli.view.GroupCreateView
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by noomerikal** [comment]
The IAM Command Line Toolkit has been deprecated in favor of the AWS CLI. In place of aws-iam-tools, use awscli:
```Shell
brew install awscli
```
then edit aws-setup-iam.sh as such (previous commands and values commented out):

```Shell
#!/usr/bin/env bash
#
# File:         aws-setup-iam.sh
# Description:  This script creates two IAM users for Wirbelsturm.

MY_DIR=`echo $(cd $(dirname $0); pwd)`
. $MY_DIR/../sh/common.sh

puts "+----------------------------------------+"
puts "| CREATING AWS IAM USERS FOR WIRBELSTURM |"
puts "+----------------------------------------+"

#IAM_PATH="/wirbelsturm"
IAM_PATH="/wirbelsturm/"
IAM_GROUP="wirbelsturm"
IN_INSTANCE_USER="wirbelsturm-ininstance"
#IN_INSTANCE_USER_POLICY_FILE=$MY_DIR/in-instance-iam-user.json
IN_INSTANCE_USER_POLICY_FILE=file://$MY_DIR/in-instance-iam-user.json
DEPLOY_USER="wirbelsturm-deploy"
#DEPLOY_USER_POLICY_FILE=$MY_DIR/deploy-iam-user.json
DEPLOY_USER_POLICY_FILE=file://$MY_DIR/deploy-iam-user.json
TIMESTAMP=`date +"%Y%m%d-%H%M%S"`

###
### IAM Group
###

puts "Creating Wirbelsturm IAM group..."
#iam-groupcreate -g $IAM_GROUP -p $IAM_PATH || exit 1
aws iam create-group --group-name $IAM_GROUP --path $IAM_PATH || exit 1

###
### Deploy IAM user
###

puts "Creating deploy IAM user '$DEPLOY_USER'..."
#iam-usercreate -u $DEPLOY_USER -g $IAM_GROUP -p $IAM_PATH || exit 1
aws iam create-user --path $IAM_PATH --user-name $DEPLOY_USER || exit 1
aws iam add-user-to-group --group-name $IAM_GROUP --user-name $DEPLOY_USER || exit 1
#KEYS=`iam-useraddkey -u $DEPLOY_USER`
KEYS=`aws iam create-access-key --user-name $DEPLOY_USER`
#DEPLOY_USER_ACCESS_KEY=`echo $KEYS | awk '{ print $1 }'`
#DEPLOY_USER_SECRET_KEY=`echo $KEYS | awk '{ print $2 }'`
DEPLOY_USER_ACCESS_KEY=`echo $KEYS | jq '.AccessKey.AccessKeyId'`
DEPLOY_USER_SECRET_KEY=`echo $KEYS | jq '.AccessKey.SecretAccessKey'`

puts "Applying security policy to IAM user '$DEPLOY_USER'..."
#iam-useruploadpolicy -u $DEPLOY_USER -f $DEPLOY_USER_POLICY_FILE \
#  -p "Deploy_IAM_user_of_Wirbelsturm_v$TIMESTAMP" || exit 1
aws iam put-user-policy --user-name $DEPLOY_USER --policy-document $DEPLOY_USER_POLICY_FILE \
  --policy-name "Deploy_IAM_user_of_Wirbelsturm_v$TIMESTAMP" || exit 1

###
### In-instance IAM user
###

puts "Creating in-instance IAM user '$IN_INSTANCE_USER'..."
#iam-usercreate -u $IN_INSTANCE_USER -g $IAM_GROUP -p $IAM_PATH || exit 1
aws iam create-user --path $IAM_PATH --user-name $IN_INSTANCE_USER || exit 1
aws iam add-user-to-group --group-name $IAM_GROUP --user-name $IN_INSTANCE_USER || exit 1
#KEYS=`iam-useraddkey -u $IN_INSTANCE_USER`
KEYS=`aws iam create-access-key --user-name $IN_INSTANCE_USER`
#IN_INSTANCE_USER_ACCESS_KEY=`echo $KEYS | awk '{ print $1 }'`
#IN_INSTANCE_USER_SECRET_KEY=`echo $KEYS | awk '{ print $2 }'`
IN_INSTANCE_USER_ACCESS_KEY=`echo $KEYS | jq '.AccessKey.AccessKeyId'`
IN_INSTANCE_USER_SECRET_KEY=`echo $KEYS | jq '.AccessKey.SecretAccessKey'`

puts "Applying security policy to IAM user '$IN_INSTANCE_USER'..."
#iam-useruploadpolicy -u $IN_INSTANCE_USER -f $IN_INSTANCE_USER_POLICY_FILE \
#  -p "In-instance_IAM_user_of_Wirbelsturm_v$TIMESTAMP" || exit 1
aws iam put-user-policy --user-name $IN_INSTANCE_USER --policy-document $IN_INSTANCE_USER_POLICY_FILE \
  --policy-name "In-instance_IAM_user_of_Wirbelsturm_v$TIMESTAMP" || exit 1

###
### Post installation
###

success "AWS IAM setup of Wirbelsturm completed!"
puts
puts "Write down the following values and add them to the 'aws' section"
puts "in your wirbelsturm.yaml configuration."
puts
puts "  Deploy IAM user:"
puts "  ---------------------"
puts "  AWS Access Key: $DEPLOY_USER_ACCESS_KEY"
puts "  AWS Secret Key: $DEPLOY_USER_SECRET_KEY"
puts
puts "  In-instance IAM user:"
puts "  ---------------------"
puts "  AWS Access Key: $IN_INSTANCE_USER_ACCESS_KEY"
puts "  AWS Secret Key: $IN_INSTANCE_USER_SECRET_KEY"
puts
```
