### ISSUE TITLE
Storm UI Error on fresh setup of cluster

### ISSUE THREAD

**Issue by samarism** [miguno/wirbelsturm#37]
Hello, thanks for this great utility. I setup wirbelsturm on MacOS 10.9.5. Everything seems to be setup fine and all the 4 nodes (zookeeper,nimbus,supervisor1,supervisor2) are running. But when I launch the storm UI I get the following error:

![aaa](https://cloud.githubusercontent.com/assets/2143346/6541450/f31e917e-c4f6-11e4-9740-b60358e3f938.png)

**Comment by samarism** [comment]
I see these entries in the nimbus.log file. Does this mean that the Nimbus daemon is unable to connect with the Zookeeper? "vagrant status" command shows that zookeeper is running. Any clues to what might be going on? Thanks.


2015-03-07 14:36:32 o.a.s.c.ConnectionState [WARN] Connection attempt unsuccessful after 22856 (greater than max timeout of 20000). Resetting connection and trying again with a new connection.
2015-03-07 14:36:32 o.a.s.z.ZooKeeper [INFO] Initiating client connection, connectString=zookeeper1:2181 sessionTimeout=20000 watcher=org.apache.storm.curator.ConnectionState@42b0014a
2015-03-07 14:36:35 b.s.d.nimbus [ERROR] Error on initialization of server service-handler
java.lang.RuntimeException: java.net.UnknownHostException: zookeeper1
	at backtype.storm.util$wrap_in_runtime.invoke(util.clj:44) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.zookeeper$exists_node_QMARK_$fn__1668.invoke(zookeeper.clj:102) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.zookeeper$exists_node_QMARK_.invoke(zookeeper.clj:98) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.zookeeper$mkdirs.invoke(zookeeper.clj:114) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.cluster$mk_distributed_cluster_state.invoke(cluster.clj:43) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.cluster$mk_storm_cluster_state.invoke(cluster.clj:238) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.nimbus$nimbus_data.invoke(nimbus.clj:67) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.nimbus$fn__5043$exec_fn__1108__auto____5044.invoke(nimbus.clj:898) ~[storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.AFn.applyToHelper(AFn.java:163) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.nimbus$fn__5043$service_handler__5133.doInvoke(nimbus.clj:895) [storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1152) [storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1184) [storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.nimbus$_main.invoke(nimbus.clj:1206) [storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.AFn.applyToHelper(AFn.java:159) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.nimbus.main(Unknown Source) [storm-core-0.9.3.jar:0.9.3]
Caused by: java.net.UnknownHostException: zookeeper1
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.7.0_75]
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901) ~[na:1.7.0_75]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293) ~[na:1.7.0_75]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1246) ~[na:1.7.0_75]
	at java.net.InetAddress.getAllByName(InetAddress.java:1162) ~[na:1.7.0_75]
	at java.net.InetAddress.getAllByName(InetAddress.java:1098) ~[na:1.7.0_75]
	at org.apache.storm.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.utils.DefaultZookeeperFactory.newZooKeeper(DefaultZookeeperFactory.java:29) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.CuratorFrameworkImpl$2.newZooKeeper(CuratorFrameworkImpl.java:174) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.HandleHolder$1.getZooKeeper(HandleHolder.java:94) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.HandleHolder.internalClose(HandleHolder.java:128) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.HandleHolder.closeAndReset(HandleHolder.java:77) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.ConnectionState.reset(ConnectionState.java:218) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.ConnectionState.checkTimeouts(ConnectionState.java:194) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.ConnectionState.getZooKeeper(ConnectionState.java:88) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:488) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:172) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.ExistsBuilderImpl$2.call(ExistsBuilderImpl.java:161) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.RetryLoop.callWithRetry(RetryLoop.java:107) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:157) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:148) ~[storm-core-0.9.3.jar:0.9.3]
	at org.apache.storm.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:36) ~[storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.zookeeper$exists_node_QMARK_$fn__1668.invoke(zookeeper.clj:101) ~[storm-core-0.9.3.jar:0.9.3]
	... 17 common frames omitted
2015-03-07 14:36:35 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) [storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.nimbus$fn__5043$service_handler__5133.doInvoke(nimbus.clj:895) [storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1152) [storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1184) [storm-core-0.9.3.jar:0.9.3]
	at backtype.storm.daemon.nimbus$_main.invoke(nimbus.clj:1206) [storm-core-0.9.3.jar:0.9.3]
	at clojure.lang.AFn.applyToHelper(AFn.java:159) [clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.nimbus.main(Unknown Source) [storm-core-0.9.3.jar:0.9.3]
[root@nimbus1 storm]#

**Comment by samarism** [comment]
Ok i did the following:
vagrant ssh zookeeper1
/usr/lib/zookeeper/bin/zkServer.sh restart
On restarting I printed the pid of the newly started zk process. But when I run "ps aux" i never see that pid. So it seems like the zookeeper process fails to launch successfully or dies as soon as it starts.

**Comment by miguno** [comment]
This "hostname unknown" issue sounds similar to the discussions at https://github.com/miguno/wirbelsturm/issues/33#issuecomment-71603772.  Can you take a look whether these instructions help you solve your problem?

**Comment by samarism** [comment]
Thank you, that was the issue. On running vagrant provision the servers started to see each other. Will use your idea of ./deploy from the next time.
